services:
  clinica-api:
    image: clinica-api:latest
    container_name: api_clinica
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9090:8080"
    networks:
      - clinica_network # Debe coincidir con la red de la BD

networks:
  clinica_network: # El nombre de la red que se crea manualmente
    external: true